name: dartmeetup1
version: 0.0.1
description: A minimal web app for the developer that doesnâ€™t want to be confused by too much going on.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  angular: any
  browser: any
  fp: any
  redstone_mapper: any
  web_components: any
transformers:
- angular
